name: build docs

on:
  #Only run on a successful test
  workflow_run:
    workflows: [Test Python Package]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  #Checkout repo
    
    #Setup python to latest version tested.
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    #Add conda
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    #Install dependencies
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda install sphinx sphinx_rtd_theme
        conda install -c conda-forge myst-parser
        
    - name: run sphinx
      run: |
        cd docs
        ./create_docs.sh
        
    # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
    - name: setup git config
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
    #Commit the new built html pages
    - name: commit build
      run: |
          echo "****** 1"
          git add docs/_build/html
          echo "****** 2"
          git diff --cached --quiet
          echo "****** 3"
          if [ $? != 0 ]
          then
            echo "****** 4"
            git commit -m 'Built latest docs'
            echo "****** 5"
            git push
          fi
          
      
