name: Trigger workflow on receiver repo

on:

  workflow_dispatch:
        

  workflow_run:
    workflows: [Test Python Package]
    types:
      - completed
 
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    
    env:
      REPO_OWNER: sam-greenwood
      REPO_NAME: thermal_history_docs
      WORKFLOW_FILENAME: build_on_dispatch.yml
       
    steps:
      - name: trigger-workflow
        run: |
          curl \
            --request POST \
            --url https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_FILENAME/dispatches \
            --header "authorization: Bearer ${{ secrets.PAT_BUILD_DOCS }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"main"}' \
            --fail
